use bakalaurinis;
CREATE TABLE Category (Id int(10) NOT NULL AUTO_INCREMENT, Name varchar(255) NOT NULL, Description varchar(512), PRIMARY KEY (Id));
CREATE TABLE Category_Problem (CategoryId int(10) NOT NULL, ProblemId int(10) NOT NULL, PRIMARY KEY (CategoryId, ProblemId));
CREATE TABLE Comment (Id int(10) NOT NULL AUTO_INCREMENT, Text varchar(5000) NOT NULL, UserId int(10) NOT NULL, ProblemId int(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE InternetUser (Id int(10) NOT NULL AUTO_INCREMENT, FirstName varchar(255) NOT NULL, LastName int(10) NOT NULL, Description varchar(512), Location varchar(255), IpAddress varchar(255), PRIMARY KEY (Id));
CREATE TABLE InternetUserDevice (Id int(10) NOT NULL AUTO_INCREMENT, Name varchar(255) NOT NULL, Manufacturer varchar(255), MacAddress varchar(255), WarrantyExpiration date, Description varchar(512), InternetUserId int(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Problem (Id int(10) NOT NULL AUTO_INCREMENT, Name varchar(255) NOT NULL, Description varchar(9000) NOT NULL, Location varchar(512), Created date NOT NULL, AssignedUser int(10) NOT NULL, StatusId int(10) NOT NULL, InternetUserId int(10) NOT NULL, CONSTRAINT Id PRIMARY KEY (Id));
CREATE TABLE Problem_Tag (TagId int(10) NOT NULL, ProblemId int(10) NOT NULL, PRIMARY KEY (TagId, ProblemId));
CREATE TABLE Status (Id int(10) NOT NULL AUTO_INCREMENT, Name int(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE `Tag` (Id int(10) NOT NULL AUTO_INCREMENT, Name varchar(50) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE TimeSpent (Id int(10) NOT NULL AUTO_INCREMENT, HoursSpent decimal(2, 0) DEFAULT 0 NOT NULL, Description varchar(512), DateRecorded timestamp DEFAULT NOW() NOT NULL, UserId int(10) NOT NULL, ProblemId int(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE `User` (Id int(10) NOT NULL AUTO_INCREMENT, FirstName varchar(50) NOT NULL, LastName varchar(50) NOT NULL, Email varchar(255) NOT NULL UNIQUE, Password varchar(255) NOT NULL, PasswordSalt varchar(255) NOT NULL, Created timestamp NOT NULL, IsDisabled tinyint NOT NULL, PRIMARY KEY (Id));
ALTER TABLE Problem ADD CONSTRAINT FKProblem611514 FOREIGN KEY (AssignedUser) REFERENCES `User` (Id);
ALTER TABLE Comment ADD CONSTRAINT FKComment537324 FOREIGN KEY (UserId) REFERENCES `User` (Id);
ALTER TABLE Comment ADD CONSTRAINT FKComment818660 FOREIGN KEY (ProblemId) REFERENCES Problem (Id);
ALTER TABLE Problem_Tag ADD CONSTRAINT FKProblem_Ta147632 FOREIGN KEY (ProblemId) REFERENCES Problem (Id);
ALTER TABLE Problem_Tag ADD CONSTRAINT FKProblem_Ta741275 FOREIGN KEY (TagId) REFERENCES `Tag` (Id);
ALTER TABLE TimeSpent ADD CONSTRAINT FKTimeSpent911204 FOREIGN KEY (UserId) REFERENCES `User` (Id);
ALTER TABLE TimeSpent ADD CONSTRAINT FKTimeSpent807458 FOREIGN KEY (ProblemId) REFERENCES Problem (Id);
ALTER TABLE Category_Problem ADD CONSTRAINT FKCategory_P899810 FOREIGN KEY (CategoryId) REFERENCES Category (Id);
ALTER TABLE Category_Problem ADD CONSTRAINT FKCategory_P650586 FOREIGN KEY (ProblemId) REFERENCES Problem (Id);
ALTER TABLE Problem ADD CONSTRAINT FKProblem836090 FOREIGN KEY (StatusId) REFERENCES Status (Id);
ALTER TABLE Problem ADD CONSTRAINT FKProblem951214 FOREIGN KEY (InternetUserId) REFERENCES InternetUser (Id);
ALTER TABLE InternetUserDevice ADD CONSTRAINT FKInternetUs985626 FOREIGN KEY (InternetUserId) REFERENCES InternetUser (Id);
